# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0005_auto_20170919_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='excl_job_flag',
            field=models.BooleanField(default=True),
        ),
    ]
