# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0006_auto_20171101_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='adtn_job_requirements',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost_app.Category'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employer_app.Employer'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='industry',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost_app.Industry'),
        ),
    ]
