# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0007_auto_20171102_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='excl_job_flag',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
