# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0008_auto_20171102_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='salary_range_flag',
            new_name='salary_range_type',
        ),
    ]
