# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0010_auto_20171102_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='excl_job_flag',
            field=models.BooleanField(default=True),
        ),
    ]
