# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0011_auto_20171103_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='last_date',
            field=models.DateField(default='', null=True),
        ),
    ]
